spring:
  datasource:
    url: jdbc:mysql://localhost/MicroserviceJpaLombok
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  port: 8080